name: "Get & Cache Dependencies"
description: "Get the dependencies (via npm) and cache them."

inputs:
  cache-key:
    required: true
    description: "The cache key to use for dependencies"

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ inputs.cache-key }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash